# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/sywrvcqgm7bf6njpfbkhd8iy4iaymhj2-cmake-3.31.6/bin/cmake

# The command to remove a file.
RM = /nix/store/sywrvcqgm7bf6njpfbkhd8iy4iaymhj2-cmake-3.31.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sameer/Documents/BlockWorld/BlockWorld

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sameer/Documents/BlockWorld/BlockWorld

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/nix/store/sywrvcqgm7bf6njpfbkhd8iy4iaymhj2-cmake-3.31.6/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nix/store/sywrvcqgm7bf6njpfbkhd8iy4iaymhj2-cmake-3.31.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sameer/Documents/BlockWorld/BlockWorld/CMakeFiles /home/sameer/Documents/BlockWorld/BlockWorld//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sameer/Documents/BlockWorld/BlockWorld/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BlockWorld

# Build rule for target.
BlockWorld: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BlockWorld
.PHONY : BlockWorld

# fast build rule for target.
BlockWorld/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/build
.PHONY : BlockWorld/fast

src/BlockWorld.o: src/BlockWorld.cpp.o
.PHONY : src/BlockWorld.o

# target to build an object file
src/BlockWorld.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/BlockWorld.cpp.o
.PHONY : src/BlockWorld.cpp.o

src/BlockWorld.i: src/BlockWorld.cpp.i
.PHONY : src/BlockWorld.i

# target to preprocess a source file
src/BlockWorld.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/BlockWorld.cpp.i
.PHONY : src/BlockWorld.cpp.i

src/BlockWorld.s: src/BlockWorld.cpp.s
.PHONY : src/BlockWorld.s

# target to generate assembly for a file
src/BlockWorld.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/BlockWorld.cpp.s
.PHONY : src/BlockWorld.cpp.s

src/ChunkBlock.o: src/ChunkBlock.cpp.o
.PHONY : src/ChunkBlock.o

# target to build an object file
src/ChunkBlock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/ChunkBlock.cpp.o
.PHONY : src/ChunkBlock.cpp.o

src/ChunkBlock.i: src/ChunkBlock.cpp.i
.PHONY : src/ChunkBlock.i

# target to preprocess a source file
src/ChunkBlock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/ChunkBlock.cpp.i
.PHONY : src/ChunkBlock.cpp.i

src/ChunkBlock.s: src/ChunkBlock.cpp.s
.PHONY : src/ChunkBlock.s

# target to generate assembly for a file
src/ChunkBlock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/ChunkBlock.cpp.s
.PHONY : src/ChunkBlock.cpp.s

src/ModelLoader/tiny_loader_texture.o: src/ModelLoader/tiny_loader_texture.cpp.o
.PHONY : src/ModelLoader/tiny_loader_texture.o

# target to build an object file
src/ModelLoader/tiny_loader_texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/ModelLoader/tiny_loader_texture.cpp.o
.PHONY : src/ModelLoader/tiny_loader_texture.cpp.o

src/ModelLoader/tiny_loader_texture.i: src/ModelLoader/tiny_loader_texture.cpp.i
.PHONY : src/ModelLoader/tiny_loader_texture.i

# target to preprocess a source file
src/ModelLoader/tiny_loader_texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/ModelLoader/tiny_loader_texture.cpp.i
.PHONY : src/ModelLoader/tiny_loader_texture.cpp.i

src/ModelLoader/tiny_loader_texture.s: src/ModelLoader/tiny_loader_texture.cpp.s
.PHONY : src/ModelLoader/tiny_loader_texture.s

# target to generate assembly for a file
src/ModelLoader/tiny_loader_texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/ModelLoader/tiny_loader_texture.cpp.s
.PHONY : src/ModelLoader/tiny_loader_texture.cpp.s

src/cube_tex.o: src/cube_tex.cpp.o
.PHONY : src/cube_tex.o

# target to build an object file
src/cube_tex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/cube_tex.cpp.o
.PHONY : src/cube_tex.cpp.o

src/cube_tex.i: src/cube_tex.cpp.i
.PHONY : src/cube_tex.i

# target to preprocess a source file
src/cube_tex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/cube_tex.cpp.i
.PHONY : src/cube_tex.cpp.i

src/cube_tex.s: src/cube_tex.cpp.s
.PHONY : src/cube_tex.s

# target to generate assembly for a file
src/cube_tex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/cube_tex.cpp.s
.PHONY : src/cube_tex.cpp.s

src/glad.o: src/glad.c.o
.PHONY : src/glad.o

# target to build an object file
src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/glad.c.o
.PHONY : src/glad.c.o

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/wrapper_glfw.o: src/wrapper_glfw.cpp.o
.PHONY : src/wrapper_glfw.o

# target to build an object file
src/wrapper_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/wrapper_glfw.cpp.o
.PHONY : src/wrapper_glfw.cpp.o

src/wrapper_glfw.i: src/wrapper_glfw.cpp.i
.PHONY : src/wrapper_glfw.i

# target to preprocess a source file
src/wrapper_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/wrapper_glfw.cpp.i
.PHONY : src/wrapper_glfw.cpp.i

src/wrapper_glfw.s: src/wrapper_glfw.cpp.s
.PHONY : src/wrapper_glfw.s

# target to generate assembly for a file
src/wrapper_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BlockWorld.dir/build.make CMakeFiles/BlockWorld.dir/src/wrapper_glfw.cpp.s
.PHONY : src/wrapper_glfw.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BlockWorld"
	@echo "... src/BlockWorld.o"
	@echo "... src/BlockWorld.i"
	@echo "... src/BlockWorld.s"
	@echo "... src/ChunkBlock.o"
	@echo "... src/ChunkBlock.i"
	@echo "... src/ChunkBlock.s"
	@echo "... src/ModelLoader/tiny_loader_texture.o"
	@echo "... src/ModelLoader/tiny_loader_texture.i"
	@echo "... src/ModelLoader/tiny_loader_texture.s"
	@echo "... src/cube_tex.o"
	@echo "... src/cube_tex.i"
	@echo "... src/cube_tex.s"
	@echo "... src/glad.o"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/wrapper_glfw.o"
	@echo "... src/wrapper_glfw.i"
	@echo "... src/wrapper_glfw.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

