
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/nix/store/sywrvcqgm7bf6njpfbkhd8iy4iaymhj2-cmake-3.31.6/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.12.51 - x86_64
...
